# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'W3lcome Face Comparison' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for W3lcome Face Comparison
  pod 'AWSCore'
  pod 'AWSRekognition'
  pod 'AWSS3'
  pod 'AWSCognito'
end
